### ISSUE TITLE
Unable to download LFS files due to data quota exceeded  

### ISSUE THREAD

**Issue by nirahs** [DhavalTaunk08/XWikiGen#1]
Hello,  
I was trying to download the `XWikiRef_part_1.zip` and `XWikiRef_part_2.zip` files from the `XWikiRef` folder using the `git lfs pull` command, but I received an error message stating that the repository is over its data quota.  

Is there any other way I can access these files? Any help would be greatly appreciated.  

Thank you.

**Comment by DhavalTaunk08** [comment]
Hi,

Please use the below link to download the dataset. Will resolve the issue in some time.

Link: [XWikiRef](https://iiitaphyd-my.sharepoint.com/:u:/g/personal/dhaval_taunk_research_iiit_ac_in/EVzrMlk7-UFMr6iJZGYU7H0Bd8TzlsY0vIAGZTOKlLqRcA?e=POh165)

**Comment by nirahs** [comment]
Thanks
